version: "3.7"

services:
  postgres:
    image: postgres:11.7-alpine
    ports:
      - "5432:5432"
    volumes:
      - ./pg-init-scripts:/docker-entrypoint-initdb.d
      - ~/factly/hukz/postgresql:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_MULTIPLE_DATABASES=hukz
    networks:
      - intranet

  hukz:
    ports:
      - 7790:7790
      - 8001:8001
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      - WAIT_HOSTS=postgres:5432, nats:4222
    volumes:
      - type: bind
        source: .
        target: /app
    restart: unless-stopped
    networks:
      - intranet

  hukz-migrate:
    build:
      context: .
      dockerfile: Dockerfile.migrate
    environment:
      - WAIT_HOSTS=postgres:5432
    volumes:
      - type: bind
        source: .
        target: /app
    networks:
      - intranet

  nats:
    depends_on:
      - hukz
    ports:
      - 4222:4222
      - 8222:8222
    image: nats:latest
    restart: unless-stopped
    networks:
      - intranet

# Add your application service (which connects with huks through nats) here.

networks:
  intranet: